//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IX4InterfaceExample.ix4WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logistikbroker.com/ServiceLayer", ConfigurationName="ix4WebService.LBAuthenticated")]
    public interface LBAuthenticated {
        
        // CODEGEN: Generating message contract since message LICSImportXMLRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://logistikbroker.com/ServiceLayer/LICSImportXMLRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IX4InterfaceExample.ix4WebService.LICSImportXMLRequestResponse LICSImportXMLRequest(IX4InterfaceExample.ix4WebService.LICSImportXMLRequestRequest request);
        
        // CODEGEN: Generating message contract since message ArticleImportCSVRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://logistikbroker.com/ServiceLayer/ArticleImportCSVRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestResponse ArticleImportCSVRequest(IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestRequest request);
        
        // CODEGEN: Generating message contract since message OrderImportCSVRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://logistikbroker.com/ServiceLayer/OrderImportCSVRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IX4InterfaceExample.ix4WebService.OrderImportCSVRequestResponse OrderImportCSVRequest(IX4InterfaceExample.ix4WebService.OrderImportCSVRequestRequest request);
        
        // CODEGEN: Generating message contract since message DeliveryImportCSVRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://logistikbroker.com/ServiceLayer/DeliveryImportCSVRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestResponse DeliveryImportCSVRequest(IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestRequest request);
        
        // CODEGEN: Generating message contract since message ExportDataRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://logistikbroker.com/ServiceLayer/ExportData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IX4InterfaceExample.ix4WebService.ExportDataResponse ExportData(IX4InterfaceExample.ix4WebService.ExportDataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
    public partial class LBSoapAuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private int clientIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LICSImportXMLRequest", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class LICSImportXMLRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
        public IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] xmlFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=1)]
        public string fileName;
        
        public LICSImportXMLRequestRequest() {
        }
        
        public LICSImportXMLRequestRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] xmlFile, string fileName) {
            this.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            this.xmlFile = xmlFile;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LICSImportXMLRequestResponse", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class LICSImportXMLRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public string LICSImportXMLRequestResult;
        
        public LICSImportXMLRequestResponse() {
        }
        
        public LICSImportXMLRequestResponse(string LICSImportXMLRequestResult) {
            this.LICSImportXMLRequestResult = LICSImportXMLRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArticleImportCSVRequest", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class ArticleImportCSVRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
        public IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] csvFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=1)]
        public string fileName;
        
        public ArticleImportCSVRequestRequest() {
        }
        
        public ArticleImportCSVRequestRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            this.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            this.csvFile = csvFile;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArticleImportCSVRequestResponse", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class ArticleImportCSVRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public string ArticleImportCSVRequestResult;
        
        public ArticleImportCSVRequestResponse() {
        }
        
        public ArticleImportCSVRequestResponse(string ArticleImportCSVRequestResult) {
            this.ArticleImportCSVRequestResult = ArticleImportCSVRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderImportCSVRequest", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class OrderImportCSVRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
        public IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] csvFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=1)]
        public string fileName;
        
        public OrderImportCSVRequestRequest() {
        }
        
        public OrderImportCSVRequestRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            this.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            this.csvFile = csvFile;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderImportCSVRequestResponse", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class OrderImportCSVRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public string OrderImportCSVRequestResult;
        
        public OrderImportCSVRequestResponse() {
        }
        
        public OrderImportCSVRequestResponse(string OrderImportCSVRequestResult) {
            this.OrderImportCSVRequestResult = OrderImportCSVRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeliveryImportCSVRequest", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class DeliveryImportCSVRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
        public IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] csvFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=1)]
        public string fileName;
        
        public DeliveryImportCSVRequestRequest() {
        }
        
        public DeliveryImportCSVRequestRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            this.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            this.csvFile = csvFile;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeliveryImportCSVRequestResponse", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class DeliveryImportCSVRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public string DeliveryImportCSVRequestResult;
        
        public DeliveryImportCSVRequestResponse() {
        }
        
        public DeliveryImportCSVRequestResponse(string DeliveryImportCSVRequestResult) {
            this.DeliveryImportCSVRequestResult = DeliveryImportCSVRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportData", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class ExportDataRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
        public IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public string requestType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=1)]
        public string[] requestParameter;
        
        public ExportDataRequest() {
        }
        
        public ExportDataRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, string requestType, string[] requestParameter) {
            this.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            this.requestType = requestType;
            this.requestParameter = requestParameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportDataResponse", WrapperNamespace="http://logistikbroker.com/ServiceLayer", IsWrapped=true)]
    public partial class ExportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://logistikbroker.com/ServiceLayer", Order=0)]
        public System.Xml.XmlNode ExportDataResult;
        
        public ExportDataResponse() {
        }
        
        public ExportDataResponse(System.Xml.XmlNode ExportDataResult) {
            this.ExportDataResult = ExportDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LBAuthenticatedChannel : IX4InterfaceExample.ix4WebService.LBAuthenticated, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LBAuthenticatedClient : System.ServiceModel.ClientBase<IX4InterfaceExample.ix4WebService.LBAuthenticated>, IX4InterfaceExample.ix4WebService.LBAuthenticated {
        
        public LBAuthenticatedClient() {
        }
        
        public LBAuthenticatedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LBAuthenticatedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LBAuthenticatedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LBAuthenticatedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IX4InterfaceExample.ix4WebService.LICSImportXMLRequestResponse IX4InterfaceExample.ix4WebService.LBAuthenticated.LICSImportXMLRequest(IX4InterfaceExample.ix4WebService.LICSImportXMLRequestRequest request) {
            return base.Channel.LICSImportXMLRequest(request);
        }
        
        public string LICSImportXMLRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] xmlFile, string fileName) {
            IX4InterfaceExample.ix4WebService.LICSImportXMLRequestRequest inValue = new IX4InterfaceExample.ix4WebService.LICSImportXMLRequestRequest();
            inValue.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            inValue.xmlFile = xmlFile;
            inValue.fileName = fileName;
            IX4InterfaceExample.ix4WebService.LICSImportXMLRequestResponse retVal = ((IX4InterfaceExample.ix4WebService.LBAuthenticated)(this)).LICSImportXMLRequest(inValue);
            return retVal.LICSImportXMLRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestResponse IX4InterfaceExample.ix4WebService.LBAuthenticated.ArticleImportCSVRequest(IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestRequest request) {
            return base.Channel.ArticleImportCSVRequest(request);
        }
        
        public string ArticleImportCSVRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestRequest inValue = new IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestRequest();
            inValue.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            inValue.csvFile = csvFile;
            inValue.fileName = fileName;
            IX4InterfaceExample.ix4WebService.ArticleImportCSVRequestResponse retVal = ((IX4InterfaceExample.ix4WebService.LBAuthenticated)(this)).ArticleImportCSVRequest(inValue);
            return retVal.ArticleImportCSVRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IX4InterfaceExample.ix4WebService.OrderImportCSVRequestResponse IX4InterfaceExample.ix4WebService.LBAuthenticated.OrderImportCSVRequest(IX4InterfaceExample.ix4WebService.OrderImportCSVRequestRequest request) {
            return base.Channel.OrderImportCSVRequest(request);
        }
        
        public string OrderImportCSVRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            IX4InterfaceExample.ix4WebService.OrderImportCSVRequestRequest inValue = new IX4InterfaceExample.ix4WebService.OrderImportCSVRequestRequest();
            inValue.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            inValue.csvFile = csvFile;
            inValue.fileName = fileName;
            IX4InterfaceExample.ix4WebService.OrderImportCSVRequestResponse retVal = ((IX4InterfaceExample.ix4WebService.LBAuthenticated)(this)).OrderImportCSVRequest(inValue);
            return retVal.OrderImportCSVRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestResponse IX4InterfaceExample.ix4WebService.LBAuthenticated.DeliveryImportCSVRequest(IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestRequest request) {
            return base.Channel.DeliveryImportCSVRequest(request);
        }
        
        public string DeliveryImportCSVRequest(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, byte[] csvFile, string fileName) {
            IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestRequest inValue = new IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestRequest();
            inValue.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            inValue.csvFile = csvFile;
            inValue.fileName = fileName;
            IX4InterfaceExample.ix4WebService.DeliveryImportCSVRequestResponse retVal = ((IX4InterfaceExample.ix4WebService.LBAuthenticated)(this)).DeliveryImportCSVRequest(inValue);
            return retVal.DeliveryImportCSVRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IX4InterfaceExample.ix4WebService.ExportDataResponse IX4InterfaceExample.ix4WebService.LBAuthenticated.ExportData(IX4InterfaceExample.ix4WebService.ExportDataRequest request) {
            return base.Channel.ExportData(request);
        }
        
        public System.Xml.XmlNode ExportData(IX4InterfaceExample.ix4WebService.LBSoapAuthenticationHeader LBSoapAuthenticationHeader, string requestType, string[] requestParameter) {
            IX4InterfaceExample.ix4WebService.ExportDataRequest inValue = new IX4InterfaceExample.ix4WebService.ExportDataRequest();
            inValue.LBSoapAuthenticationHeader = LBSoapAuthenticationHeader;
            inValue.requestType = requestType;
            inValue.requestParameter = requestParameter;
            IX4InterfaceExample.ix4WebService.ExportDataResponse retVal = ((IX4InterfaceExample.ix4WebService.LBAuthenticated)(this)).ExportData(inValue);
            return retVal.ExportDataResult;
        }
    }
}
