//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd", IsNullable=false)]
public partial class ExportDataResponse {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Content", typeof(ExportDataResponseContent))]
    [System.Xml.Serialization.XmlElementAttribute("Request", typeof(ExportDataResponseRequest))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd")]
public partial class ExportDataResponseContent {
    
    private ExportDataResponseContentSA saField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExportDataResponseContentSA SA {
        get {
            return this.saField;
        }
        set {
            this.saField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd")]
public partial class ExportDataResponseContentSA {
    
    private ExportDataResponseContentSAMSG[] mSGField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MSG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ExportDataResponseContentSAMSG[] MSG {
        get {
            return this.mSGField;
        }
        set {
            this.mSGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd")]
public partial class ExportDataResponseContentSAMSG {
    
    private string mSGHeader_TypeField;
    
    private string mSGHeader_CreatedField;
    
    private string mSGHeader_StatusField;
    
    private string mSGHeader_UserField;
    
    private string mSGPos_ItemNoField;
    
    private string mSGPos_AmountField;
    
    private string mSGPos_StorageplaceField;
    
    private string mSGPos_PurchaseOrderField;
    
    private string mSGPos_DilosProcessNoField;
    
    private string mSGPos_DilosPosField;
    
    private string mSGPos_WAPosIDField;
    
    private string mSGPos_WAKopfIDField;
    
    private string mSGPos_OrderTypeField;
    
    private string mSGPos_ShippingTypeField;
    
    private string mSGPos_BinTypeField;
    
    private string mSGPos_ResAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Type {
        get {
            return this.mSGHeader_TypeField;
        }
        set {
            this.mSGHeader_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Created {
        get {
            return this.mSGHeader_CreatedField;
        }
        set {
            this.mSGHeader_CreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Status {
        get {
            return this.mSGHeader_StatusField;
        }
        set {
            this.mSGHeader_StatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_User {
        get {
            return this.mSGHeader_UserField;
        }
        set {
            this.mSGHeader_UserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_ItemNo {
        get {
            return this.mSGPos_ItemNoField;
        }
        set {
            this.mSGPos_ItemNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_Amount {
        get {
            return this.mSGPos_AmountField;
        }
        set {
            this.mSGPos_AmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_Storageplace {
        get {
            return this.mSGPos_StorageplaceField;
        }
        set {
            this.mSGPos_StorageplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_PurchaseOrder {
        get {
            return this.mSGPos_PurchaseOrderField;
        }
        set {
            this.mSGPos_PurchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_DilosProcessNo {
        get {
            return this.mSGPos_DilosProcessNoField;
        }
        set {
            this.mSGPos_DilosProcessNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_DilosPos {
        get {
            return this.mSGPos_DilosPosField;
        }
        set {
            this.mSGPos_DilosPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_WAPosID {
        get {
            return this.mSGPos_WAPosIDField;
        }
        set {
            this.mSGPos_WAPosIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_WAKopfID {
        get {
            return this.mSGPos_WAKopfIDField;
        }
        set {
            this.mSGPos_WAKopfIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_OrderType {
        get {
            return this.mSGPos_OrderTypeField;
        }
        set {
            this.mSGPos_OrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_ShippingType {
        get {
            return this.mSGPos_ShippingTypeField;
        }
        set {
            this.mSGPos_ShippingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_BinType {
        get {
            return this.mSGPos_BinTypeField;
        }
        set {
            this.mSGPos_BinTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_ResAmount {
        get {
            return this.mSGPos_ResAmountField;
        }
        set {
            this.mSGPos_ResAmountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/ExportData/ExportDataResponse.xsd")]
public partial class ExportDataResponseRequest {
    
    private string clientIdField;
    
    private string typeField;
    
    private string tsField;
    
    private string parametersField;
    
    /// <remarks/>
    public string ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string TS {
        get {
            return this.tsField;
        }
        set {
            this.tsField = value;
        }
    }
    
    /// <remarks/>
    public string Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
}
