//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class CONTENT {
    
    private CONTENTMSG[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MSG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CONTENTMSG[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CONTENTMSG {
    
    private string mSGHeader_TypeField;
    
    private string mSGHeader_CreatedField;
    
    private string mSGHeader_StatusField;
    
    private string mSGHeader_UserField;
    
    private string mSGPos_AmountField;
    
    private string mSGPos_PurchaseOrderField;
    
    private string mSGPos_DilosProcessNoField;
    
    private string mSGPos_DilosPosField;
    
    private string mSGPos_WAPosIDField;
    
    private string mSGPos_OrderTypeField;
    
    private string mSGPos_TrackingNoField;
    
    private string mSGPos_ShippingTypeField;
    
    private string mSGPos_BinTypeField;
    
    private string mSGPos_ResAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Type {
        get {
            return this.mSGHeader_TypeField;
        }
        set {
            this.mSGHeader_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Created {
        get {
            return this.mSGHeader_CreatedField;
        }
        set {
            this.mSGHeader_CreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_Status {
        get {
            return this.mSGHeader_StatusField;
        }
        set {
            this.mSGHeader_StatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGHeader_User {
        get {
            return this.mSGHeader_UserField;
        }
        set {
            this.mSGHeader_UserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_Amount {
        get {
            return this.mSGPos_AmountField;
        }
        set {
            this.mSGPos_AmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_PurchaseOrder {
        get {
            return this.mSGPos_PurchaseOrderField;
        }
        set {
            this.mSGPos_PurchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_DilosProcessNo {
        get {
            return this.mSGPos_DilosProcessNoField;
        }
        set {
            this.mSGPos_DilosProcessNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_DilosPos {
        get {
            return this.mSGPos_DilosPosField;
        }
        set {
            this.mSGPos_DilosPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_WAPosID {
        get {
            return this.mSGPos_WAPosIDField;
        }
        set {
            this.mSGPos_WAPosIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_OrderType {
        get {
            return this.mSGPos_OrderTypeField;
        }
        set {
            this.mSGPos_OrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_TrackingNo {
        get {
            return this.mSGPos_TrackingNoField;
        }
        set {
            this.mSGPos_TrackingNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_ShippingType {
        get {
            return this.mSGPos_ShippingTypeField;
        }
        set {
            this.mSGPos_ShippingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_BinType {
        get {
            return this.mSGPos_BinTypeField;
        }
        set {
            this.mSGPos_BinTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MSGPos_ResAmount {
        get {
            return this.mSGPos_ResAmountField;
        }
        set {
            this.mSGPos_ResAmountField = value;
        }
    }
}
