//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MSG {
    
    private string mSGHeader_TypeField;
    
    private string mSGHeader_CreatedField;
    
    private string mSGHeader_StatusField;
    
    private string mSGHeader_UserField;
    
    private string mSGPos_ItemNoField;
    
    private string mSGPos_AmountField;
    
    private string mSGPos_PurchaseOrderField;
    
    private string mSGPos_DilosProcessNoField;
    
    private string mSGPos_DilosPosField;
    
    private string mSGPos_WAPosIDField;
    
    private string mSGPos_WAKopfIDField;
    
    private string mSGPos_OrderTypeField;
    
    private string mSGPos_ShippingTypeField;
    
    private string mSGPos_BinTypeField;
    
    private string mSGPos_ResAmountField;
    
    private string mSGPos_StorageplaceField;
    
    private string mSGPos_DeliveryNoField;
    
    private string mSGPos_SupplierField;
    
    private string mSGPos_TrackingNoField;

    /// <remarks/>
    
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_Type")]
    public string Type {
        get {
            return this.mSGHeader_TypeField;
        }
        set {
            this.mSGHeader_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_Created")]
    public string Created {
        get {
            return this.mSGHeader_CreatedField;
        }
        set {
            this.mSGHeader_CreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName ="MSGHeader_Status")]
    public string Status
    {
        get {
            return this.mSGHeader_StatusField;
        }
        set {
            this.mSGHeader_StatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_User")]
    public string User {
        get {
            return this.mSGHeader_UserField;
        }
        set {
            this.mSGHeader_UserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ItemNo")]
    public string ItemNo {
        get {
            return this.mSGPos_ItemNoField;
        }
        set {
            this.mSGPos_ItemNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Amount")]
    public string Amount {
        get {
            return this.mSGPos_AmountField;
        }
        set {
            this.mSGPos_AmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_PurchaseOrder")]
    public string PurchaseOrder {
        get {
            return this.mSGPos_PurchaseOrderField;
        }
        set {
            this.mSGPos_PurchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DilosProcessNo")]
    public string DilosProcessNo {
        get {
            return this.mSGPos_DilosProcessNoField;
        }
        set {
            this.mSGPos_DilosProcessNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DilosPos")]
    public string DilosPos {
        get {
            return this.mSGPos_DilosPosField;
        }
        set {
            this.mSGPos_DilosPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_WAPosID")]
    public string WAPosID {
        get {
            return this.mSGPos_WAPosIDField;
        }
        set {
            this.mSGPos_WAPosIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_WAKopfID")]
    public string WAKopfID {
        get {
            return this.mSGPos_WAKopfIDField;
        }
        set {
            this.mSGPos_WAKopfIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_OrderType")]
    public string OrderType {
        get {
            return this.mSGPos_OrderTypeField;
        }
        set {
            this.mSGPos_OrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ShippingType")]
    public string ShippingType {
        get {
            return this.mSGPos_ShippingTypeField;
        }
        set {
            this.mSGPos_ShippingTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_BinType")]
    public string BinType {
        get {
            return this.mSGPos_BinTypeField;
        }
        set {
            this.mSGPos_BinTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ResAmount")]
    public string ResAmount {
        get {
            return this.mSGPos_ResAmountField;
        }
        set {
            this.mSGPos_ResAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Storageplace")]
    public string Storageplace {
        get {
            return this.mSGPos_StorageplaceField;
        }
        set {
            this.mSGPos_StorageplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DeliveryNo")]
    public string DeliveryNo {
        get {
            return this.mSGPos_DeliveryNoField;
        }
        set {
            this.mSGPos_DeliveryNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Supplier")]
    public string Supplier {
        get {
            return this.mSGPos_SupplierField;
        }
        set {
            this.mSGPos_SupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_TrackingNo")]
    public string TrackingNo {
        get {
            return this.mSGPos_TrackingNoField;
        }
        set {
            this.mSGPos_TrackingNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private MSG[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MSG")]
    public MSG[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
