//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ix4Models.Schema.WV;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MSG {
    private int headerId;

    private bool saved;

    private string mSGHeader_TypeField;
    
    private System.DateTime mSGHeader_CreatedField;

    private System.DateTime mSGHeader_LastUpdateField;

    private string mSGHeader_ErrorTextField;

    private string mSGHeader_StatusField;
    
    private string mSGHeader_UserField;
    
    private string mSGPos_ItemNoField;
    
    private double mSGPos_AmountField;
    
    private int mSGPos_PurchaseOrderField;
    
    private int mSGPos_DilosProcessNoField;
    
    private int mSGPos_DilosPosField;
    
    private int mSGPos_WAPosIDField;
    
    private int mSGPos_WAKopfIDField;
    
    private int mSGPos_OrderTypeField;
    
    private int mSGPos_ShippingTypeField;
    
    private string mSGPos_BinTypeField;
    
    private double mSGPos_ResAmountField;
    
    private string mSGPos_StorageplaceField;
    
    private string mSGPos_DeliveryNoField;
    
    private string mSGPos_SupplierField;
    
    private string mSGPos_TrackingNoField;

    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_HeaderId")]
    [MSGSystem]
    public int HeaderId
    {
        get { return headerId; }
        set { headerId = value; }
    }

    [MSGSystem]
    public bool Saved
    {
        get { return saved; }
        set { saved = value; }
    }

    /// <remarks/>
    
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_Type")]
    [MSGHeader]
    public string Type {
        get {
            return this.mSGHeader_TypeField;
        }
        set {
            this.mSGHeader_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_Created")]
    [MSGHeader]
    public System.DateTime Created {
        get {
            return this.mSGHeader_CreatedField;
        }
        set {
            this.mSGHeader_CreatedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_LastUpdate")]
    [MSGHeader]
    public System.DateTime LastUpdate
    {
        get
        {
            return this.mSGHeader_LastUpdateField;
        }
        set
        {
            this.mSGHeader_LastUpdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName ="MSGHeader_Status")]
    [MSGHeader]
    public string Status
    {
        get {
            return this.mSGHeader_StatusField;
        }
        set {
            this.mSGHeader_StatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_ErrorText")]
    [MSGHeader]
    public string ErrorText
    {
        get
        {
            return this.mSGHeader_ErrorTextField;
        }
        set
        {
            this.mSGHeader_ErrorTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGHeader_User")]
    [MSGHeader]
    public string User {
        get {
            return this.mSGHeader_UserField;
        }
        set {
            this.mSGHeader_UserField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ItemNo")]
    [MSGPos]
    public string ItemNo {
        get {
            return this.mSGPos_ItemNoField;
        }
        set {
            this.mSGPos_ItemNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Amount")]
    [MSGPos]
    public double Amount {
        get {
            return this.mSGPos_AmountField;
        }
        set {
            this.mSGPos_AmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_PurchaseOrder")]
    [MSGPos]
    public int PurchaseOrder {
        get {
            return this.mSGPos_PurchaseOrderField;
        }
        set {
            this.mSGPos_PurchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DilosProcessNo")]
    [MSGPos]
    public int DilosProcessNo {
        get {
            return this.mSGPos_DilosProcessNoField;
        }
        set {
            this.mSGPos_DilosProcessNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DilosPos")]
    [MSGPos]
    public int DilosPos {
        get {
            return this.mSGPos_DilosPosField;
        }
        set {
            this.mSGPos_DilosPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_WAPosID")]
    [MSGPos]
    public int WAPosID {
        get {
            return this.mSGPos_WAPosIDField;
        }
        set {
            this.mSGPos_WAPosIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_WAKopfID")]
    [MSGPos]
    public int WAKopfID {
        get {
            return this.mSGPos_WAKopfIDField;
        }
        set {
            this.mSGPos_WAKopfIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_OrderType")]
    [MSGPos]
    public int OrderType {
        get {
            return this.mSGPos_OrderTypeField;
        }
        set {
            this.mSGPos_OrderTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ShippingType")]
    [MSGPos]
    public int ShippingType {
        get {
            return this.GetModifiedShippingType();
        }
        set {
            this.mSGPos_ShippingTypeField = value;
        }
    }

    private int GetModifiedShippingType()
    {
        int resultShippingType = 9;
        switch(this.mSGPos_ShippingTypeField)
        {
            case 100:
                resultShippingType = 9;
                break;
            case 900:
                resultShippingType = 1;
                break;
            case 200:
                resultShippingType = 5;
                break;
            case 800:
                resultShippingType = 6;
                break;
            case 130:
                resultShippingType = 13;
                break;
            case 0:
                resultShippingType = 19;
                break;
            default:
                break;

        }


        return resultShippingType;

    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_BinType")]
    [MSGPos]
    public string BinType {
        get {
            return this.mSGPos_BinTypeField;
        }
        set {
            this.mSGPos_BinTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_ResAmount")]
    [MSGPos]
    public double ResAmount {
        get {
            return this.mSGPos_ResAmountField;
        }
        set {
            this.mSGPos_ResAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Storageplace")]
    [MSGPos]
    public string Storageplace {
        get {
            return this.mSGPos_StorageplaceField;
        }
        set {
            this.mSGPos_StorageplaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_DeliveryNo")]
    [MSGPos]
    public string DeliveryNo {
        get {
            return this.mSGPos_DeliveryNoField;
        }
        set {
            this.mSGPos_DeliveryNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_Supplier")]
    [MSGPos]
    public string Supplier {
        get {
            return this.mSGPos_SupplierField;
        }
        set {
            this.mSGPos_SupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName = "MSGPos_TrackingNo")]
    [MSGPos]
    public string TrackingNo {
        get {
            return this.mSGPos_TrackingNoField;
        }
        set {
            this.mSGPos_TrackingNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private MSG[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MSG")]
    public MSG[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
