//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://logistikbroker.com/LICSResponse.xsd", IsNullable=false)]
public partial class LICSResponse {
    
    private int clientIdField;
    
    private int stateField;
    
    private string messageField;
    
    private LICSResponseArticleImport articleImportField;
    
    private LICSResponseOrderImport orderImportField;
    
    private LICSResponseDeliveryImport deliveryImportField;
    
    private string versionField;
    
    public LICSResponse() {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    public int ClientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public LICSResponseArticleImport ArticleImport {
        get {
            return this.articleImportField;
        }
        set {
            this.articleImportField = value;
        }
    }
    
    /// <remarks/>
    public LICSResponseOrderImport OrderImport {
        get {
            return this.orderImportField;
        }
        set {
            this.orderImportField = value;
        }
    }
    
    /// <remarks/>
    public LICSResponseDeliveryImport DeliveryImport {
        get {
            return this.deliveryImportField;
        }
        set {
            this.deliveryImportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseArticleImport {
    
    private int stateField;
    
    private string messageField;
    
    private int countOfSuccessfulField;
    
    private int countOfFailedField;
    
    private LICSResponseArticleImportArticle[] articleField;
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfSuccessful {
        get {
            return this.countOfSuccessfulField;
        }
        set {
            this.countOfSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfFailed {
        get {
            return this.countOfFailedField;
        }
        set {
            this.countOfFailedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Article")]
    public LICSResponseArticleImportArticle[] Article {
        get {
            return this.articleField;
        }
        set {
            this.articleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseArticleImportArticle {
    
    private int clientNoField;
    
    private string articleNoField;
    
    private int stateField;
    
    private string messageField;
    
    private int lICSIdField;
    
    /// <remarks/>
    public int ClientNo {
        get {
            return this.clientNoField;
        }
        set {
            this.clientNoField = value;
        }
    }
    
    /// <remarks/>
    public string ArticleNo {
        get {
            return this.articleNoField;
        }
        set {
            this.articleNoField = value;
        }
    }
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public int LICSId {
        get {
            return this.lICSIdField;
        }
        set {
            this.lICSIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseOrderImport {
    
    private int stateField;
    
    private string messageField;
    
    private int countOfSuccessfulField;
    
    private int countOfFailedField;
    
    private LICSResponseOrderImportOrder[] orderField;
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfSuccessful {
        get {
            return this.countOfSuccessfulField;
        }
        set {
            this.countOfSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfFailed {
        get {
            return this.countOfFailedField;
        }
        set {
            this.countOfFailedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Order")]
    public LICSResponseOrderImportOrder[] Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseOrderImportOrder {
    
    private int stateField;
    
    private string messageField;
    
    private string referenceNoField;
    
    private string orderNoField;
    
    private int clientNoField;
    
    private string customerNoField;
    
    private int lICSIdField;
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string ReferenceNo {
        get {
            return this.referenceNoField;
        }
        set {
            this.referenceNoField = value;
        }
    }
    
    /// <remarks/>
    public string OrderNo {
        get {
            return this.orderNoField;
        }
        set {
            this.orderNoField = value;
        }
    }
    
    /// <remarks/>
    public int ClientNo {
        get {
            return this.clientNoField;
        }
        set {
            this.clientNoField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerNo {
        get {
            return this.customerNoField;
        }
        set {
            this.customerNoField = value;
        }
    }
    
    /// <remarks/>
    public int LICSId {
        get {
            return this.lICSIdField;
        }
        set {
            this.lICSIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseDeliveryImport {
    
    private int stateField;
    
    private string messageField;
    
    private int countOfSuccessfulField;
    
    private int countOfFailedField;
    
    private LICSResponseDeliveryImportDelivery[] deliveryField;
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfSuccessful {
        get {
            return this.countOfSuccessfulField;
        }
        set {
            this.countOfSuccessfulField = value;
        }
    }
    
    /// <remarks/>
    public int CountOfFailed {
        get {
            return this.countOfFailedField;
        }
        set {
            this.countOfFailedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Delivery")]
    public LICSResponseDeliveryImportDelivery[] Delivery {
        get {
            return this.deliveryField;
        }
        set {
            this.deliveryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://logistikbroker.com/LICSResponse.xsd")]
public partial class LICSResponseDeliveryImportDelivery {
    
    private int stateField;
    
    private string messageField;
    
    private string deliveryNoField;
    
    private int clientNoField;
    
    private int lICSIdField;
    
    /// <remarks/>
    public int State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string DeliveryNo {
        get {
            return this.deliveryNoField;
        }
        set {
            this.deliveryNoField = value;
        }
    }
    
    /// <remarks/>
    public int ClientNo {
        get {
            return this.clientNoField;
        }
        set {
            this.clientNoField = value;
        }
    }
    
    /// <remarks/>
    public int LICSId {
        get {
            return this.lICSIdField;
        }
        set {
            this.lICSIdField = value;
        }
    }
}
