//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.Atoll.biz/MobileIntegrationServer/Weinwelt")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.Atoll.biz/MobileIntegrationServer/Weinwelt", IsNullable=false)]
public partial class OutputPayLoad {
    
    private OutputPayLoadOrderHeader orderHeaderField;
    
    private OutputPayLoadOutputPosition[] positionsField;
    
    private object warehouseTexteField;
    
    /// <remarks/>
    public OutputPayLoadOrderHeader OrderHeader {
        get {
            return this.orderHeaderField;
        }
        set {
            this.orderHeaderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OutputPosition", IsNullable=false)]
    public OutputPayLoadOutputPosition[] Positions {
        get {
            return this.positionsField;
        }
        set {
            this.positionsField = value;
        }
    }
    
    /// <remarks/>
    public object WarehouseTexte {
        get {
            return this.warehouseTexteField;
        }
        set {
            this.warehouseTexteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.Atoll.biz/MobileIntegrationServer/Weinwelt")]
public partial class OutputPayLoadOrderHeader {
    
    private string orderIDField;
    
    private string orderNumberField;
    
    private uint customerNumberField;
    
    private string customerNameField;
    
    private object customerName2Field;
    
    private string customerStreetField;
    
    private uint customerZIPField;
    
    private string customerTownField;
    
    private string dateField;
    
    private string warehouseOrderField;
    
    /// <remarks/>
    public string OrderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public uint CustomerNumber {
        get {
            return this.customerNumberField;
        }
        set {
            this.customerNumberField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerName {
        get {
            return this.customerNameField;
        }
        set {
            this.customerNameField = value;
        }
    }
    
    /// <remarks/>
    public object CustomerName2 {
        get {
            return this.customerName2Field;
        }
        set {
            this.customerName2Field = value;
        }
    }
    
    /// <remarks/>
    public string CustomerStreet {
        get {
            return this.customerStreetField;
        }
        set {
            this.customerStreetField = value;
        }
    }
    
    /// <remarks/>
    public uint CustomerZIP {
        get {
            return this.customerZIPField;
        }
        set {
            this.customerZIPField = value;
        }
    }
    
    /// <remarks/>
    public string CustomerTown {
        get {
            return this.customerTownField;
        }
        set {
            this.customerTownField = value;
        }
    }
    
    /// <remarks/>
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseOrder {
        get {
            return this.warehouseOrderField;
        }
        set {
            this.warehouseOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.Atoll.biz/MobileIntegrationServer/Weinwelt")]
public partial class OutputPayLoadOutputPosition {
    
    private uint articleRowNumberField;
    
    private string articleNumberField;
    
    private string warehouseField;
    
    private string descriptionField;
    
    private string description2Field;
    
    private string vPECodeField;
    
    private string vPECountField;
    
    private byte baseUnitQuantityField;
    
    private uint attachedToLineNoField;
    
    /// <remarks/>
    public uint ArticleRowNumber {
        get {
            return this.articleRowNumberField;
        }
        set {
            this.articleRowNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ArticleNumber {
        get {
            return this.articleNumberField;
        }
        set {
            this.articleNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Warehouse {
        get {
            return this.warehouseField;
        }
        set {
            this.warehouseField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Description2 {
        get {
            return this.description2Field;
        }
        set {
            this.description2Field = value;
        }
    }
    
    /// <remarks/>
    public string VPECode {
        get {
            return this.vPECodeField;
        }
        set {
            this.vPECodeField = value;
        }
    }
    
    /// <remarks/>
    public string VPECount {
        get {
            return this.vPECountField;
        }
        set {
            this.vPECountField = value;
        }
    }
    
    /// <remarks/>
    public byte BaseUnitQuantity {
        get {
            return this.baseUnitQuantityField;
        }
        set {
            this.baseUnitQuantityField = value;
        }
    }
    
    /// <remarks/>
    public uint AttachedToLineNo {
        get {
            return this.attachedToLineNoField;
        }
        set {
            this.attachedToLineNoField = value;
        }
    }
}
