//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ix4Connector.Ix4WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LBAuthenticated", Namespace="http://logistikbroker.com/ServiceLayer")]
    public partial class ix4PublicInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private LBSoapAuthenticationHeader lBSoapAuthenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback LICSImportXMLRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArticleImportCSVRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback OrderImportCSVRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryImportCSVRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExportDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ix4PublicInterface() {
            this.Url = global::Ix4Connector.Properties.Settings.Default.Ix4Connector_Ix4WebService_ix4PublicInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public LBSoapAuthenticationHeader LBSoapAuthenticationHeaderValue {
            get {
                return this.lBSoapAuthenticationHeaderValueField;
            }
            set {
                this.lBSoapAuthenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LICSImportXMLRequestCompletedEventHandler LICSImportXMLRequestCompleted;
        
        /// <remarks/>
        public event ArticleImportCSVRequestCompletedEventHandler ArticleImportCSVRequestCompleted;
        
        /// <remarks/>
        public event OrderImportCSVRequestCompletedEventHandler OrderImportCSVRequestCompleted;
        
        /// <remarks/>
        public event DeliveryImportCSVRequestCompletedEventHandler DeliveryImportCSVRequestCompleted;
        
        /// <remarks/>
        public event ExportDataCompletedEventHandler ExportDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LBSoapAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://logistikbroker.com/ServiceLayer/LICSImportXMLRequest", RequestNamespace="http://logistikbroker.com/ServiceLayer", ResponseNamespace="http://logistikbroker.com/ServiceLayer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LICSImportXMLRequest([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] xmlFile, string fileName) {
            object[] results = this.Invoke("LICSImportXMLRequest", new object[] {
                        xmlFile,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LICSImportXMLRequestAsync(byte[] xmlFile, string fileName) {
            this.LICSImportXMLRequestAsync(xmlFile, fileName, null);
        }
        
        /// <remarks/>
        public void LICSImportXMLRequestAsync(byte[] xmlFile, string fileName, object userState) {
            if ((this.LICSImportXMLRequestOperationCompleted == null)) {
                this.LICSImportXMLRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLICSImportXMLRequestOperationCompleted);
            }
            this.InvokeAsync("LICSImportXMLRequest", new object[] {
                        xmlFile,
                        fileName}, this.LICSImportXMLRequestOperationCompleted, userState);
        }
        
        private void OnLICSImportXMLRequestOperationCompleted(object arg) {
            if ((this.LICSImportXMLRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LICSImportXMLRequestCompleted(this, new LICSImportXMLRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LBSoapAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://logistikbroker.com/ServiceLayer/ArticleImportCSVRequest", RequestNamespace="http://logistikbroker.com/ServiceLayer", ResponseNamespace="http://logistikbroker.com/ServiceLayer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ArticleImportCSVRequest([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] csvFile, string fileName) {
            object[] results = this.Invoke("ArticleImportCSVRequest", new object[] {
                        csvFile,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ArticleImportCSVRequestAsync(byte[] csvFile, string fileName) {
            this.ArticleImportCSVRequestAsync(csvFile, fileName, null);
        }
        
        /// <remarks/>
        public void ArticleImportCSVRequestAsync(byte[] csvFile, string fileName, object userState) {
            if ((this.ArticleImportCSVRequestOperationCompleted == null)) {
                this.ArticleImportCSVRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArticleImportCSVRequestOperationCompleted);
            }
            this.InvokeAsync("ArticleImportCSVRequest", new object[] {
                        csvFile,
                        fileName}, this.ArticleImportCSVRequestOperationCompleted, userState);
        }
        
        private void OnArticleImportCSVRequestOperationCompleted(object arg) {
            if ((this.ArticleImportCSVRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArticleImportCSVRequestCompleted(this, new ArticleImportCSVRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LBSoapAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://logistikbroker.com/ServiceLayer/OrderImportCSVRequest", RequestNamespace="http://logistikbroker.com/ServiceLayer", ResponseNamespace="http://logistikbroker.com/ServiceLayer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OrderImportCSVRequest([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] csvFile, string fileName) {
            object[] results = this.Invoke("OrderImportCSVRequest", new object[] {
                        csvFile,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OrderImportCSVRequestAsync(byte[] csvFile, string fileName) {
            this.OrderImportCSVRequestAsync(csvFile, fileName, null);
        }
        
        /// <remarks/>
        public void OrderImportCSVRequestAsync(byte[] csvFile, string fileName, object userState) {
            if ((this.OrderImportCSVRequestOperationCompleted == null)) {
                this.OrderImportCSVRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOrderImportCSVRequestOperationCompleted);
            }
            this.InvokeAsync("OrderImportCSVRequest", new object[] {
                        csvFile,
                        fileName}, this.OrderImportCSVRequestOperationCompleted, userState);
        }
        
        private void OnOrderImportCSVRequestOperationCompleted(object arg) {
            if ((this.OrderImportCSVRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OrderImportCSVRequestCompleted(this, new OrderImportCSVRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LBSoapAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://logistikbroker.com/ServiceLayer/DeliveryImportCSVRequest", RequestNamespace="http://logistikbroker.com/ServiceLayer", ResponseNamespace="http://logistikbroker.com/ServiceLayer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeliveryImportCSVRequest([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] csvFile, string fileName) {
            object[] results = this.Invoke("DeliveryImportCSVRequest", new object[] {
                        csvFile,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryImportCSVRequestAsync(byte[] csvFile, string fileName) {
            this.DeliveryImportCSVRequestAsync(csvFile, fileName, null);
        }
        
        /// <remarks/>
        public void DeliveryImportCSVRequestAsync(byte[] csvFile, string fileName, object userState) {
            if ((this.DeliveryImportCSVRequestOperationCompleted == null)) {
                this.DeliveryImportCSVRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryImportCSVRequestOperationCompleted);
            }
            this.InvokeAsync("DeliveryImportCSVRequest", new object[] {
                        csvFile,
                        fileName}, this.DeliveryImportCSVRequestOperationCompleted, userState);
        }
        
        private void OnDeliveryImportCSVRequestOperationCompleted(object arg) {
            if ((this.DeliveryImportCSVRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryImportCSVRequestCompleted(this, new DeliveryImportCSVRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("LBSoapAuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://logistikbroker.com/ServiceLayer/ExportData", RequestNamespace="http://logistikbroker.com/ServiceLayer", ResponseNamespace="http://logistikbroker.com/ServiceLayer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ExportData(string requestType, string[] requestParameter) {
            object[] results = this.Invoke("ExportData", new object[] {
                        requestType,
                        requestParameter});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ExportDataAsync(string requestType, string[] requestParameter) {
            this.ExportDataAsync(requestType, requestParameter, null);
        }
        
        /// <remarks/>
        public void ExportDataAsync(string requestType, string[] requestParameter, object userState) {
            if ((this.ExportDataOperationCompleted == null)) {
                this.ExportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExportDataOperationCompleted);
            }
            this.InvokeAsync("ExportData", new object[] {
                        requestType,
                        requestParameter}, this.ExportDataOperationCompleted, userState);
        }
        
        private void OnExportDataOperationCompleted(object arg) {
            if ((this.ExportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExportDataCompleted(this, new ExportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://logistikbroker.com/ServiceLayer")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://logistikbroker.com/ServiceLayer", IsNullable=false)]
    public partial class LBSoapAuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private int clientIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LICSImportXMLRequestCompletedEventHandler(object sender, LICSImportXMLRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LICSImportXMLRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LICSImportXMLRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ArticleImportCSVRequestCompletedEventHandler(object sender, ArticleImportCSVRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArticleImportCSVRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArticleImportCSVRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OrderImportCSVRequestCompletedEventHandler(object sender, OrderImportCSVRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderImportCSVRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OrderImportCSVRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeliveryImportCSVRequestCompletedEventHandler(object sender, DeliveryImportCSVRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryImportCSVRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryImportCSVRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExportDataCompletedEventHandler(object sender, ExportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591